export enum IncidentCategory {
  PHISHING = "PHISHING",
  ONLINE_SCAM = "ONLINE_SCAM",
  ACCOUNT_COMPROMISE = "ACCOUNT_COMPROMISE",
  PACKAGE_THEFT = "PACKAGE_THEFT",
  BURGLARY = "BURGLARY",
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  POWER_OUTAGE = "POWER_OUTAGE",
  INTERNET_OUTAGE = "INTERNET_OUTAGE",
  FRAUD = "FRAUD",
  OTHER = "OTHER",
}
